name: GithubAction pipeline

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn package --file pom.xml 

      - name: Trivy FS scan
        run: |
          trivy fs --format table -o trivy-fs-report.html .

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_HOST }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gae-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_HOST }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t kathirvel13/githubaction_boardgame:latest .

      - name: Trivy Image Scan
        run: |
          trivy image --format table -o trivy-image-report.html kathirvel13/githubaction_boardgame:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB.TOKEN }}

      - name: Push Docker Image
        run: |
          docker push kathirvel13/githubaction_boardgame:latest

      - name: Minikube Start
        run: |
          minikube start

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment-service.yaml -n webapps
          kubectl get svc -n webapps

      - name: Minikube Stop
        run: |
          minikube stop
